// This file is auto-generated by @hey-api/openapi-ts

import { type Options, get, postRegister, postLogin, getRefreshToken, getUserProfile, postCreateAssignment, getAssignments, postSubmission, getStatusAssignments } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { GetData, PostRegisterData, PostRegisterResponse, PostLoginData, PostLoginResponse, GetRefreshTokenData, GetUserProfileData, PostCreateAssignmentData, PostCreateAssignmentResponse, GetAssignmentsData, PostSubmissionData, PostSubmissionResponse, GetStatusAssignmentsData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getQueryKey = (options?: Options<GetData>) => createQueryKey('get', options);

export const getOptions = (options?: Options<GetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await get({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getQueryKey(options)
    });
};

export const postRegisterMutation = (options?: Partial<Options<PostRegisterData>>): UseMutationOptions<PostRegisterResponse, DefaultError, Options<PostRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostRegisterResponse, DefaultError, Options<PostRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postLoginMutation = (options?: Partial<Options<PostLoginData>>): UseMutationOptions<PostLoginResponse, DefaultError, Options<PostLoginData>> => {
    const mutationOptions: UseMutationOptions<PostLoginResponse, DefaultError, Options<PostLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRefreshTokenQueryKey = (options?: Options<GetRefreshTokenData>) => createQueryKey('getRefreshToken', options);

export const getRefreshTokenOptions = (options?: Options<GetRefreshTokenData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRefreshToken({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRefreshTokenQueryKey(options)
    });
};

export const getUserProfileQueryKey = (options?: Options<GetUserProfileData>) => createQueryKey('getUserProfile', options);

export const getUserProfileOptions = (options?: Options<GetUserProfileData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUserProfile({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserProfileQueryKey(options)
    });
};

export const postCreateAssignmentMutation = (options?: Partial<Options<PostCreateAssignmentData>>): UseMutationOptions<PostCreateAssignmentResponse, DefaultError, Options<PostCreateAssignmentData>> => {
    const mutationOptions: UseMutationOptions<PostCreateAssignmentResponse, DefaultError, Options<PostCreateAssignmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCreateAssignment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAssignmentsQueryKey = (options?: Options<GetAssignmentsData>) => createQueryKey('getAssignments', options);

export const getAssignmentsOptions = (options?: Options<GetAssignmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAssignments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAssignmentsQueryKey(options)
    });
};

export const postSubmissionMutation = (options?: Partial<Options<PostSubmissionData>>): UseMutationOptions<PostSubmissionResponse, DefaultError, Options<PostSubmissionData>> => {
    const mutationOptions: UseMutationOptions<PostSubmissionResponse, DefaultError, Options<PostSubmissionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postSubmission({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStatusAssignmentsQueryKey = (options?: Options<GetStatusAssignmentsData>) => createQueryKey('getStatusAssignments', options);

export const getStatusAssignmentsOptions = (options?: Options<GetStatusAssignmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getStatusAssignments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getStatusAssignmentsQueryKey(options)
    });
};