// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
    email?: string;
    password?: string;
};

export type RegisterRequest = {
    name?: string;
    nim?: string;
    email?: string;
    password?: string;
};

export type LoginResponse = {
    message?: string;
    tokens?: {
        accessToken?: string;
        refreshToken?: string;
    };
};

export type RegisterResponse = {
    message?: string;
    data?: {
        id?: number;
        createdAt?: string;
        updatedAt?: string;
        deletedAt?: unknown;
        name?: string;
        email?: string;
        role?: string;
    };
};

export type RefreshAccessTokenResponse = {
    message?: string;
    tokens?: {
        accessToken?: string;
    };
};

export type UserProfileResponse = {
    message?: string;
    data?: {
        user?: {
            id?: number;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: unknown;
            name?: string;
            email?: string;
            role?: string;
        };
    };
};

export type CreateAssignmentRequest = {
    nama?: string;
    deskripsi?: string;
    deadline?: string;
};

export type CreateAssignmentResponse = {
    message?: string;
    data?: {
        assignment?: {
            id?: number;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: unknown;
            nama?: string;
            deskripsi?: string;
            deadline?: string;
            creator?: {
                id?: number;
                name?: string;
                email?: string;
            };
        };
    };
};

export type GetAllAssignmentByNipResponse = {
    message?: string;
    data?: {
        assignments?: Array<{
            id?: number;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: unknown;
            nama?: string;
            deskripsi?: string;
            deadline?: string;
            creator?: {
                nip?: string;
                nama?: string;
                email?: string;
            };
        }>;
    };
};

export type AddSubmissionRequest = {
    /**
     * The file to upload. Only .pdf and .doc formats are supported.
     */
    file: Blob | File;
    /**
     * The ID of the assignment to which the submission belongs.
     */
    tugasId: number;
};

export type AddSubmissionResponse = {
    message?: string;
    data?: {
        submission?: {
            id?: number;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: unknown;
            nim?: string;
            tugasId?: number;
            fileUrl?: string;
        };
    };
};

export type GetAllAssignmentStatusResponse = {
    message?: string;
    data?: Array<{
        id?: number;
        createdAt?: string;
        updatedAt?: string;
        deletedAt?: unknown;
        nama?: string;
        deskripsi?: string;
        deadline?: string;
        status?: string;
    }>;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: RegisterResponse;
    /**
     * Created
     */
    201: unknown;
};

export type PostRegisterResponse = PostRegisterResponses[keyof PostRegisterResponses];

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostLoginResponses = {
    /**
     * Login successful
     */
    200: LoginResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type GetRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/refresh-token';
};

export type GetRefreshTokenErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type GetRefreshTokenResponses = {
    /**
     * OK
     */
    200: RefreshAccessTokenResponse;
};

export type GetRefreshTokenResponse = GetRefreshTokenResponses[keyof GetRefreshTokenResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-profile';
};

export type GetUserProfileErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUserProfileResponses = {
    /**
     * User profile retrieved successfully.
     */
    200: UserProfileResponse;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type PostCreateAssignmentData = {
    body: CreateAssignmentRequest;
    path?: never;
    query?: never;
    url: '/create/assignment';
};

export type PostCreateAssignmentErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostCreateAssignmentResponses = {
    /**
     * Assignment created successfully.
     */
    200: CreateAssignmentResponse;
    /**
     * Created
     */
    201: unknown;
};

export type PostCreateAssignmentResponse = PostCreateAssignmentResponses[keyof PostCreateAssignmentResponses];

export type GetAssignmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/assignments';
};

export type GetAssignmentsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetAssignmentsResponses = {
    /**
     * Assignment created successfully.
     */
    200: GetAllAssignmentByNipResponse;
};

export type GetAssignmentsResponse = GetAssignmentsResponses[keyof GetAssignmentsResponses];

export type PostSubmissionData = {
    body: AddSubmissionRequest;
    path?: never;
    query?: never;
    url: '/submission';
};

export type PostSubmissionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostSubmissionResponses = {
    /**
     * Submission created successfully.
     */
    201: AddSubmissionResponse;
};

export type PostSubmissionResponse = PostSubmissionResponses[keyof PostSubmissionResponses];

export type GetStatusAssignmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/assignments';
};

export type GetStatusAssignmentsResponses = {
    /**
     * Submission created successfully.
     */
    200: GetAllAssignmentStatusResponse;
};

export type GetStatusAssignmentsResponse = GetStatusAssignmentsResponses[keyof GetStatusAssignmentsResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3001/api/v1' | (string & {});
};